### ISSUE TITLE
what backbone is used?

### ISSUE THREAD

**Issue by xudou3** [JDAI-CV/FaceX-Zoo#10]
Hi,

Thank you for your great work! 
In https://github.com/JDAI-CV/FaceX-Zoo/blob/main/training_mode/README.md, what backbone is used in Experiments of SOTA heads, Shallow Face Learning and Masked Face Recognition? 

Best regards.

**Comment by wang21jun** [comment]
Thank you for your interest in our work.
You can find the answers for all of your problems in our tech report: https://arxiv.org/pdf/2101.04407.pdf

**Comment by xudou3** [comment]
Thank you for your replay. I'll check that.
