### ISSUE TITLE
能否提供face_detection_retina.pkl和face_landmark_pfld.pkl对应的ONNX模型

### ISSUE THREAD

**Issue by guijuzhejiang** [JDAI-CV/FaceX-Zoo#109]
感谢您分享的出色工作。我在项目中只找到了pkl模型，mobilefacenet模型通过您提供的pt文件可以专程ONNX模型，请问能否提供人脸识别和关键点检测的ONNX模型？或者请教如何从现有的pkl模型转换ONNX模型的方法。

**Comment by XJX777** [comment]
> 感谢您分享的出色工作。我在项目中只找到了pkl模型，mobilefacenet模型通过您提供的pt文件可以专程ONNX模型，请问能否提供人脸识别和关键点检测的ONNX模型？或者请教如何从现有的pkl模型转换ONNX模型的方法。

你好，本项目中可以参照FaceX-Zoo/addition_module/model_convertor/convert_to_onnx/model_convert.py中**21行convert函数**的ONNX模型转换方法，也可参照https://blog.csdn.net/qq_50444970/article/details/119791855中的**pytorch模型转onnx**部分。

**Comment by XJX777** [comment]
> 感谢您分享的出色工作。我在项目中只找到了pkl模型，mobilefacenet模型通过您提供的pt文件可以专程ONNX模型，请问能否提供人脸识别和关键点检测的ONNX模型？或者请教如何从现有的pkl模型转换ONNX模型的方法。

你好，本项目中可以参照FaceX-Zoo/addition_module/model_convertor/convert_to_onnx/model_convert.py中21行convert函数的ONNX模型转换方法，也可参照 https://blog.csdn.net/qq_50444970/article/details/119791855中的pytorch模型转onnx部分。

**Comment by XJX777** [comment]
> 感谢您分享的出色工作。我在项目中只找到了pkl模型，mobilefacenet模型通过您提供的pt文件可以专程ONNX模型，请问能否提供人脸识别和关键点检测的ONNX模型？或者请教如何从现有的pkl模型转换ONNX模型的方法。

你好，本项目中可以参照FaceX-Zoo/addition_module/model_convertor/convert_to_onnx/model_convert.py中21行convert函数的ONNX模型转换方法，也可参照  https://blog.csdn.net/qq_50444970/article/details/119791855  中的pytorch模型转onnx部分。

**Comment by guijuzhejiang** [comment]
谢谢，直接用pkl模型转换了ONNX模型。目测可用

**Comment by Hondlus** [comment]
> 谢谢，直接用pkl模型转换了ONNX模型。目测可用

你好，请问您是怎么将pkl转onnx的，能分享一下源码或onnx模型吗？谢谢
