### ISSUE TITLE
Semi-Siamese Training: How to choose appropriate queue_size

### ISSUE THREAD

**Issue by vmthanh** [JDAI-CV/FaceX-Zoo#110]
Hi
I tried with "Semi-Siamese Training" and found a config named **queue_size** in the **training_mode/head_config.yaml**. 

`SST_Prototype:
    queue_size: 16384 #is divisible by batch size.`

When I read in the paper "**Semi-Siamese Training for Shallow Face Learning**", author mentioned that 

> The size of the gallery queue depends on the number of classes in training datasets, so we empirically set it as 16,384 for shallow and deep data, and 2,560 for QMULSurvFace. 

May I ask how to choose appropriate queue_size with given a custom dataset

Thank you.

**Comment by wang21jun** [comment]
If your dataset is big enough, just set it to 16384 or 32768.
If your dataset is a small one, you can try any sizes which are multiples of the training batch size, but it must be smaller than the class numbers.

**Comment by vmthanh** [comment]
> If your dataset is big enough, just set it to 16384 or 32768. If your dataset is a small one, you can try any sizes which are multiples of the training batch size, but it must be smaller than the class numbers.

Got this. Thanks so much
