### ISSUE TITLE
关于其他模型如何训练

### ISSUE THREAD

**Issue by xiaozhubenben** [JDAI-CV/FaceX-Zoo#112]
请问,如何训练face_detect face_align  这些模型呢?

**Comment by wang21jun** [comment]
你好，该仓库主要用于训练人脸识别的特征提取模型，detect和align模型参考其他项目，比如：
Pytorch_Retinaface, ChainerCV, pfld_106_face_landmarks等等都是非常优秀的项目．

**Comment by xiaozhubenben** [comment]
了解了. 之前主要是不清楚pipeline 中用到的几个模型是哪里来的,还以为是本项目带这些模型训练方法. 谢谢您的回答
