### ISSUE TITLE
retinaface可以直接输出人脸5个关键点，为什么还要用alignment？

### ISSUE THREAD

**Issue by liuxufenfeiya** [JDAI-CV/FaceX-Zoo#115]
看face_detect的代码，在输出检测结果的时候，是有关键点landms的
`loc, conf, landms = self.model(image)`
不过后处理并没有使用这个，不知道是不是精度不够？
后面单独的alignment模型虽然输出136个关键点，但也只用了5个，是否有点重复了？

**Comment by wang21jun** [comment]
你好！retinaface的五个点确实可以满足识别切图需要．
单独做alignment模型一方面是提供更高的关键点精度，另一方面也希望该高精度的106关键点能支持到其他应用，比如口罩添加算法．https://github.com/JDAI-CV/FaceX-Zoo/tree/main/addition_module/face_mask_adding/FMA-3D
