### ISSUE TITLE
Is there a live estimation application

### ISSUE THREAD

**Issue by guijuzhejiang** [JDAI-CV/FaceX-Zoo#16]
It seems that there is no live estimation framework yet.Will the live estimation be added in the future?

**Comment by wang21jun** [comment]
Thanks for your advise. We will consider to do it in the future. Before that, you can estimate the models by our provided face sdk: FaceX-Zoo/face_sdk

**Comment by guijuzhejiang** [comment]
Okay thank you. Thank you for your open source work.
