### ISSUE TITLE
Masked Face Recognition数据集

### ISSUE THREAD

**Issue by leoluopy** [JDAI-CV/FaceX-Zoo#26]
Masked Face Recognition 的指标是出自这个数据集的测试吗？

https://github.com/X-zhangyang/Real-World-Masked-Face-Dataset

**Comment by wang21jun** [comment]
不是。
Masked Face Recognition 训练数据为 MS-Celeb-1M-v1c-Mask，测试数据为MegaFace-Mask，详见tech-report。https://arxiv.org/pdf/2101.04407.pdf

**Comment by FunkyKoki** [comment]
实验设置可以参看 [technical report](https://arxiv.org/abs/2101.04407)

**Comment by leoluopy** [comment]
great thanks to all of u
