### ISSUE TITLE
Caught AttributeError in DataLoader worker process 0

### ISSUE THREAD

**Issue by buimanhlinh96** [JDAI-CV/FaceX-Zoo#31]
Hi FaceX-Zoo team,
I faced a issue "AttributeError: Caught AttributeError in DataLoader worker process 0" when i trained.
I trained with default setting except the num_class i set 1020 equal to my custom dataset.
How can i solve this problem? Thank you so much!!!
![Screenshot from 2021-02-03 17-12-50](https://user-images.githubusercontent.com/61372071/106732408-4025e780-6643-11eb-83e7-36259771da49.png)

**Comment by buimanhlinh96** [comment]
1.My folder structure
![Screenshot from 2021-02-03 17-24-05](https://user-images.githubusercontent.com/61372071/106733585-a828fd80-6644-11eb-9484-5f7ef48e077a.png)
2. My train_list.txt
![Screenshot from 2021-02-03 17-24-49](https://user-images.githubusercontent.com/61372071/106733722-d0186100-6644-11eb-89f6-9ef168c544da.png)

**Comment by wang21jun** [comment]
The loaded image is empty. 
If you confirm that the image is not empty, please check 'data_root' and 'train_file'.

**Comment by buimanhlinh96** [comment]
1. This is my folder structrue, VNceleb is folder containing data
![Screenshot from 2021-02-03 17-24-05](https://user-images.githubusercontent.com/61372071/106750245-293ebf80-665a-11eb-8512-0cac5b4819db.png)
2. This is my train file
![Screenshot from 2021-02-03 17-24-49](https://user-images.githubusercontent.com/61372071/106750336-4f645f80-665a-11eb-9635-918f55ed3ff6.png)

**Comment by buimanhlinh96** [comment]
My train.sh
mkdir 'log'
python3 train.py \
    --data_root '/home/linh/Desktop/AI_LUMI/FaceX-Zoo/tutorial_lumi/VN-celeb-112' \
    --train_file '/home/linh/Desktop/AI_LUMI/FaceX-Zoo/tutorial_lumi/vnceleb_train_list.txt' \
    --backbone_type 'ResNet' \
    --backbone_conf_file '../backbone_conf.yaml' \
    --head_type 'AdaM-Softmax' \
    --head_conf_file '../head_conf.yaml' \
    --lr 0.1 \
    --out_dir 'out_dir' \
    --epoches 18 \
    --step '10, 13, 16' \
    --print_freq 200 \
    --save_freq 3000 \
    --batch_size 8 \
    --momentum 0.9 \
    --log_dir 'log' \
    --tensorboardx_logdir 'ResNet' \
    --pretrain_model '/home/linh/Desktop/AI_LUMI/FaceX-Zoo/pretrained_model/backbone/Resnet152.pt'
    2>&1 | tee log/log.log
