### ISSUE TITLE
Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (function expandTensors)

### ISSUE THREAD

**Issue by buimanhlinh96** [JDAI-CV/FaceX-Zoo#35]
Hi FaceX-Zoo team,
I face a warning while training: "[W IndexingUtils.h:25] Warning: indexing with dtype torch.uint8 is now deprecated, please use a dtype torch.bool instead. (function expandTensors)"
I used warnings lib of python3 but it didnt work :(?
Can you solve this problem

**Comment by liuxufenfeiya** [comment]
i met the same problem and i used igrone warnings but it was useless.
i try to change the version of the torch to 1.1.0,but the cudnn is not fit.
