### ISSUE TITLE
Test face_pipline.py on CPU

### ISSUE THREAD

**Issue by marziehoghbaie** [JDAI-CV/FaceX-Zoo#40]
Hi, 
I like to test face_pipline.py on cpu, but I keep taking the following error:
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
However, I changed the device to CPU.

**Comment by docongminh** [comment]
@marziehoghbaie  I have same problem and i fixed it and commit in [here](https://github.com/docongminh/FaceX-Zoo/commit/74bcadbcf270eeaabb41a59aa6927ca26acb721b)

**Comment by marziehoghbaie** [comment]
> 
> 
> @marziehoghbaie I have same problem and i fixed it and commit in [here](https://github.com/docongminh/FaceX-Zoo/commit/74bcadbcf270eeaabb41a59aa6927ca26acb721b)

Thanks a lot, it worked :+1:
