### ISSUE TITLE
请问这个工程可以识别小人脸吗？

### ISSUE THREAD

**Issue by Kingstom8MB** [JDAI-CV/FaceX-Zoo#41]
我有一些小人脸要识别身份，最小的是18X18，是运行face_detect.py进行人脸识别吗？我运行后他说识别失败，人脸都框不出来，更别提后续的训练了，想问一下他可不可以识别小人脸，还是说我需要调整一些参数。英语不好对着谷歌浏览器的翻译看了一下没怎么明白，来请教一下

**Comment by Kingstom8MB** [comment]
我之前是使用PyFaceDet识别到了足够小的人脸，现在需要通过人脸确认身份。卡在身份识别这里，不知道这个工程能不能训练那么小的人脸数据，来请教一下

**Comment by wang21jun** [comment]
您好！该工程并没有针对小人脸做过优化。

**Comment by Kingstom8MB** [comment]
@wang21jun 那请问一下你知道有哪个工程可以做小人脸的身份检测吗？
