### ISSUE TITLE
Wear mask to face but it changes my image quality 

### ISSUE THREAD

**Issue by cannguyen275** [JDAI-CV/FaceX-Zoo#43]
Hello,

Let's explain the issue with below samples:
![42](https://user-images.githubusercontent.com/35292523/108336660-dbec5180-7206-11eb-9d36-22ba072f1c50.jpg)
![42_masked](https://user-images.githubusercontent.com/35292523/108336676-e0186f00-7206-11eb-9bb6-92b8a26b8a49.jpg)

I use **add_mask_one** script, **is_aug** is **False** but sometimes, it somehow changes the whole image content. I just want to wear a mask without effect to my image quality.

**Comment by wang21jun** [comment]
Could you please upload your original image (without landmarks and mask) ?

**Comment by cannguyen275** [comment]
Sure! Pls check it out.
![42](https://user-images.githubusercontent.com/35292523/108458739-d09d3280-72a7-11eb-8cd6-f1f2a2964e39.jpg)

**Comment by wang21jun** [comment]
![mask_false](https://user-images.githubusercontent.com/19286339/108527288-13452600-730d-11eb-9ee9-16234cb2a29c.jpg)
![test1_landmark_res0](https://user-images.githubusercontent.com/19286339/108527319-1b04ca80-730d-11eb-9c97-1b570e01df45.jpg)
![test1_mask1](https://user-images.githubusercontent.com/19286339/108527335-1f30e800-730d-11eb-8ed0-ee2b630bcdd8.jpg)
This is my result by the original add_mask_one.py with  is_aug=False.

**Comment by cannguyen275** [comment]
Yes, it's the reason why I've used "sometimes, somehow" in my question. I've customized the add_mask_one.py to be able to run many images in a folder, keep all other codes as the original. But the error randomly occurred each time I ran.

Below images are from 2 times I ran in the same folder. Pls focus on image 90_masked.jpg/ 120_masked.jpg:

![Screenshot from 2021-02-22 13-42-36](https://user-images.githubusercontent.com/35292523/108672192-40175a00-7514-11eb-924c-5cc13263b967.png)
-----
![Screenshot from 2021-02-22 13-42-58](https://user-images.githubusercontent.com/35292523/108672197-4279b400-7514-11eb-9928-1e33de5c91fe.png)

**Comment by annopackage** [comment]
Hi, have you solved this problem? I encountered similar question.

**Comment by cannguyen275** [comment]
> Hi, have you solved this problem? I encountered similar question.

I solved it by change: 

https://github.com/JDAI-CV/FaceX-Zoo/blob/71402463e8c4cd8b279482452c6cb82da92b50f8/addition_module/face_mask_adding/FMA-3D/face_masker.py#L170
to 
```python
imsave(masked_face_path, skimage.img_as_ubyte(new_image))
```
