### ISSUE TITLE
Face recognition score

### ISSUE THREAD

**Issue by buiduchanh** [JDAI-CV/FaceX-Zoo#59]
@wang21jun  Hello, 
I have a small question, In this project you used cosine similarity for caculate score between 2 feature. This score can be negative so I wanna normalize it between 0 and 1. Can you share the solution to do it ? 
Thanks

**Comment by mundanePeo** [comment]
me too， please！

**Comment by wang21jun** [comment]
sim = 0.5 + 0.5*cos(theta)

**Comment by buiduchanh** [comment]
@wang21jun 
I saw : score = np.dot(feature1 , feature2 ) 
=> Sim = 0.5 + 0.5 * cos(score) 
Is this right ?

**Comment by mundanePeo** [comment]
> @wang21jun
> I saw : score = np.dot(feature1 , feature2 )
> => Sim = 0.5 + 0.5 * cos(score)
> Is this right ?

isn't score cos？why is not “sim=0.5+0.5*score”?

**Comment by buiduchanh** [comment]
> > @wang21jun
> > I saw : score = np.dot(feature1 , feature2 )
> > => Sim = 0.5 + 0.5 * cos(score)
> > Is this right ?
> 
> isn't score cos？why is not “sim=0.5+0.5*score”?

I think score is cosine distance so the value is degree in radian

**Comment by wang21jun** [comment]
cos(theta) = score = np.dot(feature1 , feature2 )

**Comment by mundanePeo** [comment]
> > > @wang21jun
> > > I saw : score = np.dot(feature1 , feature2 )
> > > => Sim = 0.5 + 0.5 * cos(score)
> > > Is this right ?
> > 
> > 
> > isn't score cos？why is not “sim=0.5+0.5*score”?
> 
> I think score is cosine distance so the value is degree in radian

aoao，tks

**Comment by mundanePeo** [comment]
> cos(theta) = score = np.dot(feature1 , feature2 )

Tks for your reply
