### ISSUE TITLE
mask face recognition

### ISSUE THREAD

**Issue by carry-xz** [JDAI-CV/FaceX-Zoo#62]
nice work 
In the technical report “model2 is also trained on MS-Celeb1M-v1c, but only the upper half of face is cropped for training,” “contains the masked probe images and remains the gallery images non-masked” . 
When testing , crop  probe img and not crop gallery img should resize to same size?  Do you try just erase bottom of the img and keep the img size for training?

**Comment by wang21jun** [comment]
Both probe images and gallery images are cropped for evaluation on model2.
erase bottom of the image and keep the image size for training will take a larger input size(112*112) but have the same useful part with our setting, so we think it's a better way to take the upper half of face as input.
