### ISSUE TITLE
module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu

### ISSUE THREAD

**Issue by apophatique** [JDAI-CV/FaceX-Zoo#68]
I start the project on cpu, but getting an error
`
    module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
`
Please tell me how to fix it? I changed loaders with 'cuda:0' -> 'cpu', also i added map_location parameter, but it still doesn't help

**Comment by docongminh** [comment]
Try model = model.module.cpu()

**Comment by apophatique** [comment]
@docongminh thanks for an answer, but it doesn't help

**Comment by caigang2501** [comment]
> Try `model = model.module.cpu() `

泪目

**Comment by caigang2501** [comment]
@docongminh 泪目
