### ISSUE TITLE
About making a mask UV texture map templates 

### ISSUE THREAD

**Issue by Gary-Deeplearning** [JDAI-CV/FaceX-Zoo#7]
This is a great repo, thanks for sharing.

I have some problems here. I want to make some new  mask UV texture map templates for myself. Could you please provide the uv_mask.png and process scripts? thank you.

**Comment by wang21jun** [comment]
Thanks for your interest in our project. 
Given a masked face image R, we first compute the uv position map P by PRNet. Then we obtain the 'uv_mask.png' by map the segmentation map of R into uv space with the uv position map P.

**Comment by Gary-Deeplearning** [comment]
Thanks for your reply.
I also used this method to make a new mask template a few days ago, but the quality of the new mask template actually depends on the quality of 'uv_mask.png'.

**Comment by sky186** [comment]
@Ga

> 
> 
> Thanks for your reply.
> I also used this method to make a new mask template a few days ago, but the quality of the new mask template actually depends on the quality of 'uv_mask.png'.

Hi,
I also want to make new mask_template (the author provide 0.png - 7.png) , 
I read your answers, but I still don't understand，So I would like to ask you how to do it！

**Comment by sky186** [comment]
@Ga

> 
> 
> Thanks for your reply.
> I also used this method to make a new mask template a few days ago, but the quality of the new mask template actually depends on the quality of 'uv_mask.png'.

Hi,
I also want to make new mask_template (the author provide 0.png - 7.png) , 
I read your answers, but I still don't understand，So I would like to ask you how to do it！

**Comment by sky186** [comment]
@Ga

> 
> 
> Thanks for your reply.
> I also used this method to make a new mask template a few days ago, but the quality of the new mask template actually depends on the quality of 'uv_mask.png'.

Hi,
I also want to make new mask_template (the author provide 0.png - 7.png) , 
I read your answers, but I still don't understand，So I would like to ask you how to do it！

**Comment by sky186** [comment]
@Ga

> 
> 
> Thanks for your reply.
> I also used this method to make a new mask template a few days ago, but the quality of the new mask template actually depends on the quality of 'uv_mask.png'.

Hi,
I also want to make new mask_template (the author provide 0.png - 7.png) , 
I read your answers, but I still don't understand，So I would like to ask you how to do it！

**Comment by sky186** [comment]
@Ga

> 
> 
> Thanks for your reply.
> I also used this method to make a new mask template a few days ago, but the quality of the new mask template actually depends on the quality of 'uv_mask.png'.

Hi,
I also want to make new mask_template (the author provide 0.png - 7.png) , 
I read your answers, but I still don't understand，So I would like to ask you how to do it！

**Comment by AlonZolfi** [comment]
@Gary-Deeplearning Have a figured out how to create a texture for the mask only?
