### ISSUE TITLE
'MobileFaceNet' object has no attribute '_non_persistent_buffers_set'

### ISSUE THREAD

**Issue by deep-practice** [JDAI-CV/FaceX-Zoo#8]
pytorch 1.6.0
torchvision 0.7.0

**Comment by wang21jun** [comment]
Thanks for your feedback! I will try to reproduce this problem, but before that, you can try to run this project with pytorch==1.1.0 and torchvision==0.3.0

**Comment by deep-practice** [comment]
Ok.

**Comment by ElegantLin** [comment]
Hi, @deep-practice ,

Do you solve the problem by changing the version of framework?

Thanks

**Comment by BuxianChen** [comment]
I tried this failed
pytorch 1.6.0
torchvision 0.7.0

But this succeed
pytorch 1.9.0
torchvision 0.10.0
