### ISSUE TITLE
face_sdk/api_usage里面所有.py文件报同一个错误

### ISSUE THREAD

**Issue by xturnip** [JDAI-CV/FaceX-Zoo#82]
windows平台下使用命令行方式和pycharm都报错：      KeyError: 'formatters'

自己尝试的解决方法：
import os
import logging.config
log_path = "config\logging.conf"
log_file_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), log_path)
print(log_file_path)
logging.config.fileConfig(log_file_path)
logger = logging.getLogger("api")
未能解决！！
向大神请教

**Comment by DLRook1e** [comment]
I also encountered the same problem. How did you solve it?
