### ISSUE TITLE
what's the difference between Attention-56 and Attention-92(MX)

### ISSUE THREAD

**Issue by wuyuuu** [JDAI-CV/FaceX-Zoo#96]
Hi, 

I found the trained models in https://github.com/JDAI-CV/FaceX-Zoo/tree/main/training_mode, where you offer Attention-56 and Attention-92(MX).

However, when I looked at backbone codes [backbone](https://github.com/JDAI-CV/FaceX-Zoo/blob/2b5af6c18441a4ae91de5bf5726210af8d52b114/backbone/AttentionNets.py#L201) and [backboneconf](https://github.com/JDAI-CV/FaceX-Zoo/blob/main/training_mode/backbone_conf.yaml), I only saw a single model and configuration.

As I am gonna use your models as feature extraction backbones, I am wondering how to initialize those two backbones (Attention-56 and Attention-92(MX)) properly.

Looking forward to your reply.
Thanks!

**Comment by wang21jun** [comment]
They share the same backbone, but the configuration is different.
AttentionNet56:
AttentionNet:
    stage1_modules: 1
    stage2_modules: 1
    stage3_modules: 1
    feat_dim: 512
    out_h: 7
    out_w: 7

AttentionNet92:
AttentionNet:
    stage1_modules: 1
    stage2_modules: 2
    stage3_modules: 3
    feat_dim: 512
    out_h: 7
    out_w: 7

**Comment by wuyuuu** [comment]
> They share the same backbone, but the configuration is different. AttentionNet56: AttentionNet: stage1_modules: 1 stage2_modules: 1 stage3_modules: 1 feat_dim: 512 out_h: 7 out_w: 7
> 
> AttentionNet92: AttentionNet: stage1_modules: 1 stage2_modules: 2 stage3_modules: 3 feat_dim: 512 out_h: 7 out_w: 7

Get it, thanks for your answer!
